apiVersion: batch/v1
kind: CronJob
metadata:
  name: job-hunting-agent-cron
  namespace: job-agent
spec:
  schedule: "0 */2 * * *" # Runs every 2 hours
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: registry.gitlab.com/ai_job_hunt-group/ai_job_hunt-project:f5f95ce3  # <-- Yeh line add karni hai
          containers:
          - name: job-agent
            image: __IMAGE_PLACEHOLDER__
            imagePullPolicy: Always
            env:
            - name: PLAYWRIGHT_ENDPOINT
              value: "ws://playwright-service.job-agent.svc.cluster.local:3000"
            - name: GMAIL_USER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: agent-secrets
                  key: GMAIL_USER_EMAIL
            - name: GMAIL_APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: agent-secrets
                  key: GMAIL_APP_PASSWORD
            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: agent-secrets
                  key: GROQ_API_KEY
          restartPolicy: OnFailure